apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cp4ba-cloud-pak-deployer-demos-run-
spec:
  timeouts:
    pipeline: 9h0m0s
  pipelineRef:
    name: cp4ba-cloud-pak-deployer-demos
