apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cp4ba-cloud-pak-deployer-demos-run-
spec:
  timeouts:
    pipeline: 9h0m0s
  pipelineRef:
    name: cp4ba-cloud-pak-deployer-demos
  params:
    - name: cloud-pak-deployer-image-tag
      value: "latest"
    - name: co-generated-users-password
      value: "-generated-"
